import React from 'react'
import { useState,useEffect } from 'react'
import FormField from '../components/FormField'
import Card from '../components/Card'
import Loader from '../components/Loader'


const RenderCards = ({ data, title }) => {
    if (data?.length> 0) {
    return data.map((post) => <Card key={post. id} {...post} />)
}
else {
    return<h2 className="mt-5 font-bold text-white text-xl uppercase">{title}</h2>
}}



const Home = () => {
    const [loading, setloading] = useState(false);
    const [allpost, setallpost] = useState(null);
    const [searchText, setsearchText] = useState("sad");
  return (
    <section>
<div className="bg-gray-900 p-10 rounded-lg shadow-2xl text-white text-center " style={{ backgroundImage: "url('https://i.gifer.com/Sr86.gif')", backgroundSize: "cover", backgroundPosition: "center" }}>
  <h1 className="text-4xl font-bold mt-2 text-indigo-300 relative z-10">Community Showcase</h1>
  <p className="text-lg mb-8  text-indigo-100 ">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
</div>



<div className=' text-indigo-200'>
    <FormField/>
    
</div>

<div className=' text-indigo-200'>
    {
    loading? (
        <div className='flex justify-center item-center'>
         <Loader/>
        </div>
    ) : (
        <>
       {searchText && (
      <h2 className= "font-medium text- [#666e75] text-xl mb-3">
        Showing results for<span className=" text-[#222328]">
            {searchText}</span> 
      </h2> )}


      <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-3 grid-cols-1 gap-3">
        {
          searchText?(
            <RenderCards data={[]} title="No result for search"/>
          ):(
            <RenderCards
            data={[]}
            title="No posts found"
            />
          )
        }
      </div>
    
</>
    )}
    </div>
      
    </section>
   

  )
}

export default Home